config/routes.rb
Rails.application.routes.draw do
  resources :highlights
  resources :meetings

  root to: "meetings#index"
  namespace 'api' do
    resources :highlights
    resources :meetings, only: [ :index, :create, :show, :update, :destroy ] do
      resources :highlights, only: [ :index, :create, :show, :update, :destroy ]
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/timeable.rb
# frozen_string_literal: true

module Timeable
  extend ActiveSupport::Concern
  include ActiveModel::Validations

  included do
    validates :start_time, presence: true
    validate :sane_time

    private

    def sane_time
      errors.add(:start_time, 'Please enter sane time range') if end_time.present? &&
                                                                 start_time.present? &&
                                                                 start_time > end_time
    end
  end
end

app/models/highlight.rb
# frozen_string_literal: true

class Highlight < ApplicationRecord
  include Timeable
  belongs_to :meeting, inverse_of: :highlights

  validates :meeting, presence: true
  validates :highligh_text, presence: true
end

app/models/meeting.rb
# frozen_string_literal: true

class Meeting < ApplicationRecord
  include Timeable
  has_many :highlights, dependent: :destroy
  validates :title, presence: true
  validates :organizer_email, presence: true
  validates :organizer_email, format: { with: URI::MailTo::EMAIL_REGEXP }

  mount_uploader :audio_file, AudioFileUploader
end

app/controllers/api/highlights_controller.rb
# frozen_string_literal: true

module Api
  class HighlightsController < ApplicationController
    before_action :set_highlight, only: %i[show update destroy]

    def index
      @highlights = params[:meeting_id] ? Meeting.find(params[:meeting_id]).highlights : Highlight.all
      render json: @highlights
    end

    def show
      render json: @highlight
    end

    def create
      @highlight = Highlight.new(highlight_params)

      if @highlight.save
        render json: @highlight, status: :created, location: @highlight
      else
        render @highlight.errors.full_messages.as_json, status: :bad_request
      end
    end

    def update
      if @highlight.update(highlight_params)
        head :no_content
      else
        render @highlight.errors.full_messages.as_json, status: :unprocessable_entity
      end
    end

    def destroy
      @highlight.destroy
      head :no_content
    end

    private

    def set_highlight
      @highlight = Highlight.find(params[:id])
    end

    def highlight_params
      params.require(:highlight).permit(:meeting_id, :start_time, :end_time, :highligh_text)
    end
  end
end

app/controllers/api/meetings_controller.rb
# frozen_string_literal: true

module Api
  class MeetingsController < ApplicationController
    before_action :set_meeting, only: %i[show update destroy]

    def index
      @meetings = Meeting.all
      render json: @meetings
    end

    def show
      render json: @meeting
    end

    def create
      @meeting = Meeting.new(meetings_params)

      if @meeting.save
        render json: @meeting, status: :created, location: @meeting
      else
        render @meeting.errors.full_messages.as_json, status: :bad_request
      end
    end

    def update
      if @meeting.update(meetings_params)
        head :no_content
      else
        render @meeting.errors.full_messages.as_json, status: :unprocessable_entity
      end
    end

    def destroy
      @meeting.destroy
      head :no_content
    end

    private

    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    def meetings_params
      params.require(:meeting).permit(:title, :organizer_email, :start_time, :end_time, :audio_file)
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/highlights_controller.rb
# frozen_string_literal: true

class HighlightsController < ApplicationController
  before_action :set_highlight, only: %i[show edit update destroy]

  # GET /highlights
  def index
    @highlights = Highlight.all
  end

  # GET /highlights/1
  def show
  end

  # GET /highlights/new
  def new
    @meeting = Meeting.find(params[:meeting_id]) if params[:meeting_id]
    @selected_meeting_id = selected_meeting_id
    @highlight = Highlight.new
  end

  # GET /highlights/1/edit
  def edit
  end

  # POST /highlights
  def create
    @highlight = Highlight.new(highlight_params)

    if @highlight.save
      redirect_to @highlight, notice: 'Highlight was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /highlights/1
  def update
    if @highlight.update(highlight_params)
      redirect_to @highlight, notice: 'Highlight was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /highlights/1
  def destroy
    @highlight.destroy
    redirect_back fallback_location: root_path, notice: 'Highlight was successfully destroyed.'
  end

  private

  def selected_meeting_id
    @highlight.try(:meeting).try(:id) || @meeting.try(:id)
  end

  def set_highlight
    @highlight = Highlight.find(params[:id])
  end

  def highlight_params
    params.require(:highlight).permit(:meeting_id, :start_time, :end_time, :highligh_text)
  end
end

app/controllers/meetings_controller.rb
# frozen_string_literal: true

class MeetingsController < ApplicationController
  before_action :set_meeting, only: %i[show edit update destroy]

  # GET /meetings
  def index
    @meetings = Meeting.all
  end

  # GET /meetings/1
  def show
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings
  def create
    @meeting = Meeting.new(meeting_params)

    if @meeting.save
      redirect_to @meeting, notice: 'Meeting was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /meetings/1
  def update
    if @meeting.update(meeting_params)
      redirect_to @meeting, notice: 'Meeting was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /meetings/1
  def destroy
    @meeting.destroy
    redirect_to meetings_url, notice: 'Meeting was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_meeting
    @meeting = Meeting.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def meeting_params
    params.require(:meeting).permit(:title, :organizer_email, :start_time, :end_time, :audio_file)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/highlights_helper.rb
module HighlightsHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/highlights/_form.html.erb
<%= form_with(model: highlight, local: true) do |form| %>
  <% if highlight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(highlight.errors.count, "error") %> prohibited this highlight from being saved:</h2>

      <ul>
      <% highlight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :meeting_id %>
    <%= form.select :meeting_id, Meeting.all.collect {|p| [ p.title, p.id ] }, {include_blank: false, selected: @selected_meeting_id, required: 'required'} %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time, id: :highlight_start_time, required: 'required' %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time, id: :highlight_end_time, required: 'required' %>
  </div>

  <div class="field">
    <%= form.label :highligh_text %>
    <%= form.text_area :highligh_text, id: :highlight_highligh_text, required: 'required' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/highlights/edit.html.erb
<h1>Editing Highlight</h1>

<%= render 'form', highlight: @highlight %>

<%= link_to 'Show', @highlight %> |
<%= link_to 'Back', highlights_path %>

app/views/highlights/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Highlights</h1>

<table class='sortable-table'>
  <thead>
    <tr>
      <th>Meeting</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Highligh text</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @highlights.each do |highlight| %>
      <tr>
        <td><%= link_to highlight.meeting.title, meeting_path(highlight.meeting) %></td>
        <td><%= highlight.start_time %></td>
        <td><%= highlight.end_time %></td>
        <td><%= highlight.highligh_text %></td>
        <td>
          <%= link_to 'Show', highlight %>
          <%= link_to 'Edit', edit_highlight_path(highlight) %>
          <%= link_to 'Destroy', highlight, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Highlight', new_highlight_path %>

app/views/highlights/new.html.erb
<h1>New Highlight</h1>

<%= render 'form', highlight: @highlight %>


<% if @meeting.present? %>
  <%= link_to 'Back', meeting_path(@meeting) %>
<% else %>
  <%= link_to 'Back', highlights_path %>
<% end %>

app/views/highlights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Meeting:</strong>
  <%= link_to @highlight.meeting.title, meeting_path(@highlight.meeting.id) %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @highlight.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @highlight.end_time %>
</p>

<p>
  <strong>Highligh text:</strong>
  <%= @highlight.highligh_text %>
</p>

<%= link_to 'Edit', edit_highlight_path(@highlight) %> |
<%= link_to 'Back', meeting_path(@highlight.meeting) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VoiceraChallenge</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/meetings/_form.html.erb
<%= form_with(model: meeting, local: true) do |form| %>
  <% if meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
      <% meeting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :meeting_title, required: 'required' %>
  </div>

  <div class="field">
    <%= form.label :organizer_email %>
    <%= form.text_field :organizer_email, id: :meeting_organizer_email, required: 'required' %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time, id: :meeting_start_time, required: 'required' %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time, id: :meeting_end_time, required: 'required' %>
  </div>

  <div class="field">
    <%= form.label :audio_file %>
    <%= form.file_field :audio_file %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/meetings/edit.html.erb
<h1>Editing Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Show', @meeting %> |
<%= link_to 'Back', meetings_path %>

app/views/meetings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Meetings</h1>

<table class='sortable-table'>
  <thead>
    <tr>
      <th>Title</th>
      <th>Organizer email</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Audio file location</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @meetings.each do |meeting| %>
      <tr>
        <td><%= meeting.title %></td>
        <td><%= meeting.organizer_email %></td>
        <td><%= meeting.start_time %></td>
        <td><%= meeting.end_time %></td>
        <td><%= meeting.audio_file %></td>
        <td>
          <%= link_to 'Show', meeting %>
          <%= link_to 'Edit', edit_meeting_path(meeting) %>
          <%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meeting', new_meeting_path %>

app/views/meetings/new.html.erb
<h1>New Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Back', meetings_path %>

app/views/meetings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @meeting.title %>
</p>

<p>
  <strong>Organizer email:</strong>
  <%= @meeting.organizer_email %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @meeting.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @meeting.end_time %>
</p>

<p>
  <strong>Audio file:</strong>
  <%= @meeting.audio_file %>
</p>

<% if @meeting.highlights.any? %>
  <h4>Highlights</h4>

  <table class='sortable-table'>
    <thead>
      <tr>
        <th>Start time</th>
        <th>End time</th>
        <th>Highligh text</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @meeting.highlights.each do |highlight| %>
        <tr>
          <td><%= highlight.start_time %></td>
          <td><%= highlight.end_time %></td>
          <td><%= highlight.highligh_text %></td>
          <td>
            <%= link_to 'Show', highlight %>
            <%= link_to 'Edit', edit_highlight_path(highlight) %>
            <%= link_to 'Destroy', highlight, method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
<%= link_to 'New Highlight', new_highlight_path(meeting_id: @meeting.id) %>

<%= link_to 'Edit', edit_meeting_path(@meeting) %> |
<%= link_to 'Back', meetings_path %>